# The URL the site will be built for
base_url = "https://orthosquare.github.io"

# To avoid problems with some variables due to multilingual support,
# you will find repeated variables in the language section,
# it is recommended that you keep those of your language and the general
# ones with the same data.
default_language = "en"
theme = "ataraxia"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feed = true
feed_filename="atom.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

minify_html = false
hard_link_static = false

[languages]
    [languages.en]
        title = "An Orthgonal Square"
        description = "Computation and combinatorics"
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]

    [languages.en.translations]
        post = "Post"
        category = "Category"
        tag = "Tag"
        search = "Search"

        404_message = "Page not found"

        by = "By"
        posted = "Posted"
        updated = "Updated"
        categories = "Categories"
        tags = "Tags"
        share = "Share"
        
        next = "Next"
        previous = "Previous"

        short_copyright = "Some rights reserved."
        full_copyright = """\
            Except where otherwise noted, the blog posts on this site are \
            licensed under the Creative Commons Attribution 4.0 International \
            (CC BY 4.0) License by the author.\
            """

[markdown]
    # Whether to do syntax highlighting
    # Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
    highlight_code = true
    highlight_theme = "base16-ocean-dark"
    render_emoji = true

    external_links_target_blank = true
    external_links_no_follow = true
    external_links_no_referrer = true

    smart_punctuation = false

[search]
    include_title = true
    include_description = false
    include_path = false
    include_content = true

[link_checker]
    # skip_prefixes = []
    # skip_anchor_prefixes = []

    internal_level = "error"
    external_level = "error"
    
[slugify]
    paths = "on"
    taxonomies = "on"
    anchors = "on"

[extra]
    author = "Michael Gill"

    # Use a square image (same height as width)
    avatar = "images/avatar.jpg"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "en_US"

    # Ataraxia uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Home", url = "@/_index.md", icon = "bi-house" },
            { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },
            { name = "About", url = "@/about.md", icon = "bi-file-earmark-person" },
            # { name = "Contact me", url = "@/contact_me.md", icon = "bi-person-vcard"}
        
        ]
    
    [extra.social]
        author_link = "#"
        twitter = "@orthosq"
        links = [
            { name = "Email", url = "mailto:michael.gill1@monash.edu", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/orthosquare", icon = "bi-github" },
            { name = "Twitter", url = "https://twitter.com/orthosq", icon = "bi-twitter" }
        ]

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"
